# Product Schema for Product Model
from src.db.ma import ma
from marshmallow import fields, validate

class ProductSchema(ma.Schema):
    id = fields.Int(dump_only=True) # auto-generated by DB, don't require it on input
    name = fields.Str(
        required=True,
        validate=validate.Length(min=1, max=100),
        error_messages={ 
            "required": "Product name is required.",
            "length": "Minimum length should be 1, maximum is 100."
        }
    )
    description = fields.Str(
        required=False,
        validate=validate.Length(max=120),
        error_messages={
            "length": "Description cannot exceed 120 characters."
        }
    )
    price = fields.Float(
        required=True,
        validate=validate.Range(min=0),
        error_messages={
            "required": "Price is required.",
            "range": "Price must be a positive number."
        }
    )
    qty = fields.Int(
        required=True,
        error_messages={
            "required": "Quantity is required",
            "range": "Quantity must be a non-negative integer."
        }
    )

